### ISSUE TITLE
[ XDMoD 6.5.0 Centos 7.3 ] Issue:The role to which you are assigned does not have access to the information you requested.

### ISSUE THREAD

**Issue by dspatil7768** [ubccr/xdmod-supremm#31]
I have installed `XDMoD 6.5.0` and above that `SUPReMM`.

Now when is `open XDMoD-SUPReMM` in web-browser it showing below error:

`The role to which you are assigned does not have access to the information you requested.`

![image](https://cloud.githubusercontent.com/assets/22992849/24707229/6fa0413a-1a30-11e7-8626-cc5cddd13aca.png)

**Comment by jtpalmer** [comment]
The default admin account doesn't have access to SUPReMM data.  You need to add the appropriate role to your user in the admin dashboard.

Please refer to http://supremm.xdmod.org/supremm-install-rpm.html or http://supremm.xdmod.org/supremm-install-source.html

> Note that the admin user that was created in the Open XDMoD does not have a user role by default and therefore cannot view SUPReMM data. If you login to XDMoD using the admin user account you will see a popup dialog box with the error message “Job Viewer: The Quick Job Lookup resource list failed to load. (The role to which you are assigned does not have access to the information you requested.)”. If you try to select SUPReMM realm data in the Usage tab then you should see an “access denied” message box. These messages should not be seen when accessing the portal using a normal account that has user role. If desired, a user role can be added to the admin account using the “User Management” tab in the XDMoD Dashboard.

**Comment by dspatil7768** [comment]
Thank you
